title: "Bivalent Cytokine Analysis Project"

project:
  output-dir: _output
  preview:
    port: 7777

format:
  typst:
    mainfont: "Times New Roman"
    monofont: "Times New Roman"
    citeproc: true
    include-in-header:
      - manuscript/_subfig-caption-override.typ
jupyter: python3

crossref:
  custom:
    - kind: float
      key: suppfig
      reference-prefix: "Figure S"

execute:
  echo: false
  warning: true
  error: false

margin: {left: 2cm, right: 2cm}
