[tool.poetry]
name = "bicytok"
version = "0.1.0"
description = ""
authors = ["Aaron Meyer <ameyer@ucla.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.26"
pandas = "^2.2"
scipy = "^1.13"
seaborn = "^0.13"
numba = "^0.59"
pot = "^0.9.0"
scikit-learn = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^8.1"
pytest-cov = "^5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "bicytok.figures.common:genFigure"
