[tool.poetry]
name = "bicytok"
version = "0.1.0"
description = ""
authors = ["Aaron Meyer <ameyer@ucla.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.24"
pandas = "1.5.3"
scipy = "^1.10"
seaborn = "0.11.2"
numba = "0.57.0rc1"
pot = "^0.9.0"
scikit-learn = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "bicytok.figures.common:genFigure"
