# Introduction

## Outline

* P1: Immunomodulatory receptors are key therapeutic targets but generate limiting off-target effects.
    + Molecules that interact with surface receptors are the largest class of therapeutics.
    + Immunomodulatory receptors often dictate immune cell function and are thus involved in a broad range of immune-mediated diseases.
    + Two properties of immune receptors:
        * Shared receptor expression across cells of different functions leads to off-target binding
        * Cellular pleiotropy leads to counteractive signals in off-target cells
    + Combined, these features lead to off-target binding which produces signals that counteract the desired effect (at best) and generate severe adverse effects (at worst)
    + Immunomodulatory ligands are rarely adopted because of severe adverse effects that arise from off-target binding.
* P2: Protein engineering efforts have reduced off-target binding through avidity-dependent targeting.
    + The promise of immunomodulatory molecules has spurred extensive protein engineering efforts aimed at reducing off-target binding
    + Chief among these are multivalent, affinity-engineered cytokine muteins fused to targeted antibody scaffolds (targeted, multispecific cytokine fusions) 
    + Coordinated changes in affinity and valency allow these molecules to preferentially bind target cells despite modest differences in receptor expression between target and off-target populations.
    + These molecules owe this so-called cell-type selectivity to avidity effects wherein low-affinity, multivalent molecules require high receptor density to bind effectively
* P3: Often, binding is all that matters.
    + Multispecific molecules with decoupled signaling and targeting domains have been shown to further enhance cell-type selectivity
    + In these cases, high-affinity and/or high-valency targeting subunits direct signal domain binding toward target cells, while low-affinity signal domains are unable to bind off-target cells despite high signal receptor density
    + Similarly, antibody-drug conjugates use targeting domains to direct cytotoxic payloads based on surface protein expression
    + Considering only the targeting function of surface proteins reveals a vast number of potential surface targets which might be exploited alone or in combination.
* P4: Combinatorial complexity has left the development of multispecific, targeted therapeutics unguided.
    + Evolution has granted us with thousands of unique surface proteins
    + These proteins may, in some combination, facilitate perfectly selective delivery of signal to any given cell type
    + However, the number of possible combinations of surface proteins is combinatorially large
    + This complexity has left the field of multispecificity unguided and siloed.
    + Even systematic explorations neglect to comprehensively evaluate the selectivity of the large space of possible targets, especially across different target cell types
* P5: Here, we use a high-throughput computational platform to systematically explore the multi-receptor targeting space and identify key properties of multispecificity.

## Body

Immunomodulatory receptors are key drug targets that remain inaccessible due to the tradeoff between acute toxicity and therapeutic efficacy. This class of surface proteins---including cytokine and chemokine receptors, co-stimulatory and co-inhibitory receptors, Fc receptors, and more---mediates nearly every immune function through their ability to bind diverse ligands and elicit context-dependent signaling [@Kirby2021, @LaPorte2008, @McFarlane2022, @Zoler2024]. While evolutionarily useful, the complexity of immune cell signaling has hindered the development of therapeutics targeting this class of receptors. Specifically, cellular pleiotropy, wherein a single receptor is expressed on diverse cell types and elicits distinct phenotypic outcomes depending on cellular context, leads to counterproductive signaling in off-target cells and dose-limiting toxicities. Coordinated changes in ligand affinity and valency have improved the safety of immunomodulatory proteins by directing binding toward target cells at the cost of reduced overall binding and potency/efficacy.

Immunomodulatory receptors are key therapeutic targets due to their ability to mediate diverse immune functions. A vast network of ligand-receptor interactions arms immune cells with the ability to sense and respond to environmental cues ranging from viral infections to tumorigenesis. Conversely, dysregulation of ligand-receptor interactions is associated with a number of diseases, including cancer, autoimmunity, and infectious disease. Harnessing the immunomodulatory capabilities of these receptors constitutes a major step toward controlling immune functions to treat these diseases.

Two properties of immune cell signaling lead to dose-limiting toxicities that hinder the therapeutic utility of immunomodulatory receptors. First, immune receptors are rarely uniquely expressed on cells of a single function---distinct cell types express similar amounts and kinds of surface proteins [@Khaled2025, @Cui2023]. Second, the signal generated upon binding these receptors is heavily influenced by cellular context (immunomodulatory proteins are pleiotropic) [@Kirby2021, @LaPorte2008, @McFarlane2022, @Zoler2024]. As a result, ligands bind their cognate receptors on both target and off-target cells and induce distinct, counterproductive responses from each cell type [@Baldo2014]. For example, systemically administered interleukin-2 (IL-2) binds IL-2 receptor (IL-2R) on both regulatory T cells (T~reg~s) and natural killer (NK) cells, leading to expansion of both cell types [@Krieg2010]. When the goal is elicit immunosuppression through selective activation of T~reg~s, the concurrent expansion of pro-inflammatory NK cells counteracts the desired immunosuppression and leads to severe toxicities [@Krieg2010, @Lim2023].

Protein engineering has improved the safety and efficacy of immunomodulatory proteins but is limited by the off-target expression of signaling receptors. Amino-acid sequence mutations confer receptor-subunit--level affinity tuning, leading to preferential binding based on differences in receptor subunit expression [@Levin2012]. Multivalent ligand complexes exploit avidity effects, or increases in local ligand concentrations upon binding, to achieve enhanced sensitivity to subtle differences in receptor density between populations of cells [@Bell2015]. Coordinated changes in affinity and valency have produced highly selective molecules with improved safety profiles [@Tan2021-intbio]. For example, tetravalent IL-2 with enhanced affinity for the T~reg~-associated $\alpha$ receptor subunit selectively binds T~reg~s over toxicity-inducing NK cells [@Peterson2018, @Orcutt-Jahns2023]. However, the extent by which engineering methods can improve selectivity is constrained by high off-target expression of signaling receptors. In the case of IL-2, $\alpha$-biased fusions are prone to binding activated cytotoxic T cells that express significant levels of IL-2R$\alpha$, which can worsen the inflammation that is the target of T~reg~ proliferation.

Multispecific ligand complexes decouple signaling from targeting to avoid the constraints of off-target expression. These molecules generally drive binding toward target cells through high-affinity "targeting" subunits (e.g., signal-incompetent cytokine muteins, antibodies, or de novo binders), whose cognate receptors are uniquely expressed on target cells. Once bound, multispecific molecules exert their effects locally either through avidity-driven binding of low-affinity "signaling" subunits (e.g., cytokine muteins, growth factors, or agonistic antibodies) or through local exposure/release of payloads (e.g., chemotherapeutics via antibody--drug conjugates, mRNA via targeted nanoparticles, or biotoxins via immunotoxins). In either case, target receptor binding is the key determinant of cell-type selectivity. Optimizing multispecific ligand design for target cell binding independently from signaling unlocks a vast number of potential surface proteins which, when targeted in some combination, might enable uniquely selective delivery to any given cell type.

The design multispecific proteins is bottlenecked by the combinatorial complexity of possible target combinations. Here, we aim to systematically explore the combinatorial targeting space under a receptor-oriented lens to identify key properties of multi-receptor targeting and guide multispecific drug design. To this end, we apply a series of high-throughput computational techniques to single-cell surface protein expression data to evaluate the selectivity of many possible surface target combinations. We find that a mechanistic binding model is the most robust and biologically interpretable metric of cell-type selectivity. Using this model, we show that at low valency, selectivity is optimized by maximizing the number of ligands for a single defining target receptor rather than employing multi-receptor targeting. We show that nearly every target exhibits synergy in selectivity when paired with some other receptor, but only high-valency, asymmetric ligand designs are able to exploit this synergy to achieve benefit beyond single-receptor targeting. Finally, we show that synergy arises as a result of dynamic differences in absolute expression between target receptors. In sum, these results point multispecific protein engineering efforts towards high-valency, asymmetric ligands that target receptors with variable expression in order to achieve optimal cell-type selectivity.

Notes:
  - Combine P1-2 into a single paragraph? "Immunomodulatory receptors are key drug targets, but their therapeutic utility is stymied by off-target binding." However, the same feature that gives these targets their functional diversity also limits their therapeutic utility.
  - The range of cellular responses is compounded by pleiotropy, where a single receptor can elicit distinct signaling outcomes depending on the cell type in which it is expressed. The result is a rich class of therapeutic targets that are involved in nearly every immune function.
  - Need to embed more context about current engineering efforts involving multiple binders. Perhaps even an entire paragraph...
  - Should problem scope be defined here with a paragraph on methods people use to get past it? **This is the last paragraph.** Swap out summary paragraph with limitations of current methods.
    - Huge in vitro screens
    - Brute force binder combination testing
    - Filtering based on expression data
    - Limitations: lack flexibility, forcing people to either explore the full space of combinations at a very high level or to deeply explore a very confined problem.
  - The current version of the intro reads more like a textbook. I think it could get to the point much faster, combine P1 and 2, then combine P3 and 4, then jump into current research strategies.
  - When discussing the limitations of protein engineering methods, potentially discuss the fact that there is tradeoff between potency and safety that is likely the culprit of failed attempts like IL-2 for liver transplant.