# Figure 1: A computational framework allows for the comprehensive evaluation of multispecific cell-type selectivity

::: {#fig-figure-1}

Overview of the multispecific cell-type-selectivity problem and the experimental and computational framework used to evaluate candidate receptor targets.
:::

## Outline

* Number of combinations to consider is huge: pairs/triads of receptors, all cell populations
* Methods of increasing complexity and computational cost:
  + Target/off-target distribution shape
  + KL divergence
  + W distance
  + The binding model.
* The experimental framework:
  + CITE-seq approximates surface protein expression at single-cell resolution
  + We define a set of possible surface targets pairs and target cell types
  + Some surface proteins are lowly expressed and have higher expression in off-target cells than target cells. These are filtered on a per-target-cell-type basis
  + For every target pair/target cell type combination, we evaluate selectivity based on EMD, KL divergence, and binding model

* In order to guide drug design, we needed a faithful predictor of the cell-type selectivity of a given combination of targets.
* In order to evaluate different predictors, we needed a faithful quantitative description of a large number of candidate target receptors.
* Given that a molecule's selectivity is largely determined by the distribution in expression of its cognate receptors across target and off-target cells, this description needed to be high resolution and defined across diverse cell types.
* Based on these criteria, we chose a CITE-seq dataset comprised of 230 unique surface proteins measured across 160,000 PBMCs spanning 30 distinct cell types.
* After filtering for lowly expressed proteins, we defined a set of 130 surface proteins that, together, comprise over 9,000 unique target pairs or 400,000 unique target triads. We then evaluated the selectivity of each target pair for all 30 cell types, resulting in over 270,000 unique target pair/cell type combinations.


* A ligand's propensity to selectively bind a given cell type is largely determined by the heterogeneity in expression of its cognate receptors within and across target and off-target cells [@Tan2021-intbio].
  + Guided by this principle, we hypothesized that we could leverage high-resolution surface protein expression data to efficiently predict the selectivity of many target combinations to map the combinatorially large multispecific targeting space.
  + Seeking a comprehensive, yet faithful, description of immune receptor expression, we chose a single-cell dataset describing the expression of 228 surface proteins across 160,000 PBMCs, generated by Cellular Indexing of Transcriptomes and Epitopes by Sequencing (CITE-seq) [@Hao2018].
  + To maintain as general a description of immune cell selectivity as possible, we labeled the PBMCs with a pre-defined set of granular cell type annotations derived from a Weighted Nearest Neighbor (WNN) analysis of the CITE-seq data, resulting in 30 immune cell subtypes spanning B cells, CD4+ T cells, CD8+ T cells, dendritic cells (DCs), monocytes, and NK cells [@Hao2018].
  + After filtering for lowly expressed proteins, we were left with a set of 134 surface proteins that, together, comprise over 9,000 unique target pairs and 270,000 unique target pair--cell type combinations (@fig-target-combinatorics).
* To guide our selection of suitable analysis methods, we defined the core methodological requirements for a useful/viable cell-type--selectivity predictor.
  + Before relying on the possibility that the individual selectivities of two targets could be extrapolated to predict the selectivity of those targets in combination, it was first necessary to evaluate the selectivity of every target combination directly in order to prove/disprove this hypothesis.
  + This goal necessitated two criteria: **(1)** a useful method must be able to evaluate the selectivity of a given target combination in a non-independent manner, and **(2)**, a useful method must be computationally efficient enough to evaluate the selectivity of thousands of target combinations in a feasible time frame.
  <!-- Move this to figure 2. Minimum requirements are joint distribution analyses and computational efficiency. The below are requirements of the results, not the methods themselves.
  + Further, CITE-seq uses antibody-derived tags (ADTs) to quantify surface protein expression, which come with a number of limitations that, in sum, lead to unreliable quantification of absolute protein expression.
  + As such, a third criterion for a useful method was that it must be invariant to the scale of a target's absolute expression.
  + Finally, one noted advance of CITE-seq was the ability to better define cell states based on the combined expression of mRNA and surface proteins through a classification tool called Weighted Nearest Neighbor (WNN) analysis [@Hao2018].
  + To maintain the comprehensive granularity of the WNN-defined cell types, a fourth criterion for a useful method was that it must not be circular in its target identification---highly selective targets must not be purely driven by the surface proteins used in cell type classification.
  -->
* Armed with a comprehensive description of immune receptor expression and a set of methodological requirements, we devised a series of computational approaches capable of efficiently quantifying the selectivity of a given set of targets from their protein expression.
  + The simplest approach to predict a single protein's selectivity is to directly compare its expression in target and off-target cells through differences or ratios of statistical features, such as their moments, geometric means, outlier weights, or shapes (@fig-raw-hists). 
  + However, these simple statistical features do not extend to arbitrary dimensions, so we turned to metrics that quantify the differences between joint probability distributions between any number of proteins.
  + Kullback--Leibler (KL) divergence is a computationally inexpensive measurement of the information lost (divergence) when one probability distribution is used to approximate another (@fig-KL-diagram).
  + Wasserstein distance (commonly referred to as Earth Mover's Distance; EMD) is a more complex optimal transport metric that measures the minimum cost (distance) of transforming one probability distribution into another (@fig-EMD-diagram).
  + KL divergence and EMD each quantify distinct statistical differences between a target protein's expression distribution in target and off-target cells (@fig-dist-features), are computationally cheap (@fig-dist-metric-speed), <!--, are both scale-invariant in at least one dimension (@fig-scale-EMD and @fig-scale-KL), --> and can both be applied to joint distributions of arbitrary dimensions, making them suitable for evaluating the selectivity of multiple targets simultaneously.
* While EMD and KL divergence meet our core requirements, they are limited in flexibility and mechanistic insight.
  + To obtain a more flexible, mechanistic description of cell-type selectivity, we explored a previously published model of multivalent binding designed to predict equilibrium receptor binding of ligand complexes composed of varying numbers and kinds of binding subunits (@fig-multivalent-binding) [@tan2021-mathbiosci].
  + Where EMD and KL divergence answer the question: how well does X composition of receptors distinguish this target cell type from other cell types, the binding model uses receptor expression to simulate the amount of binding that would occur for a ligand targeting those receptors.
  + Further, the binding model is unique in its flexibility: it can be applied to explore total ligand valency, valency of individual binding subunits, affinity between individual subunits and receptors, and ligand avidity through a global cross-linking constant.
  + Finally, the model can better evaluate the multispecific paradigm by including a designated "signaling" ligand, and optimizing model parameters such as affinity and cross-linking to maximize selective binding of the signaling ligand for a target cell type (@fig-optimization-schematic).
  + The nested optimization of the binding model came at a computational cost, so we optimized the model infrastructure using GPU acceleration, just-in-time (JIT) compilation, and starting point selection to achieve the necessary computational efficiency (@fig-binding-model-speed).
