name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        version: '0.39.0'
    - name: Setup environment
      run: make .venv
    - name: Render all figures
      run: quarto render figures/ --to typst
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: figures
        path: |
          _output/figures/